### ISSUE TITLE
Circular references

### ISSUE THREAD

**Issue by ekes** [localgovdrupal/localgov_guides#6]
Review:

Are the back references created on saving guide pages on the overview page the best way of doing this?

**Comment by ekes** [comment]
If the references remain - there should be handling for deleted entities. Normally this is fine, the reference is ignored if the entity no longer exists, but the pagination is also using the deltas so an effectively empty page is placed in the order (till it is removed form the reference field).

**Comment by stephen-cox** [comment]
So just as there's a hook_node_update() function to add a page to the overview's `localgov_guides_pages` field (https://github.com/localgovdrupal/localgov_guides/blob/master/localgov_guides.module#L37) there needs to be a hook_entity_delete() function to remove the page.

**Comment by stephen-cox** [comment]
The changes in #15 remove the kernel tests linked above, but this is still a problem with the new tests for the prev and next links block.

https://github.com/localgovdrupal/localgov_guides/blob/d3c77d0422badd8f9ae43677d1404c899487c449/tests/src/Functional/PrevNextBlockTest.php#L99

**Comment by ekes** [comment]
> So just as there's a hook_node_update() function to add a page to the overview's localgov_guides_pages field there needs to be a hook_entity_delete() function to remove the page.

That's probably the simplest solution for now. That and removing it if it's updated and no longer references.

There's a bigger issue about refactoring this and the very similar step-by-step that works in a quite different way, but I think 'works for now'™ and will probably hit review if/when sub-steps need to added to step-by-step.

**Comment by stephen-cox** [comment]
@ekes I think I solved this for campaigns.

- Node update hook: https://github.com/localgovdrupal/localgov_campaigns/blob/ed71f9955d8c97efa17d10bf4bd3f65f232a6a03/localgov_campaigns.module#L54
- Node delete hook: https://github.com/localgovdrupal/localgov_campaigns/blob/ed71f9955d8c97efa17d10bf4bd3f65f232a6a03/localgov_campaigns.module#L79

Can this simply be fixed by adjusted this code?

**Comment by finnlewis** [comment]
@ekes is this relevant to today's problem on https://github.com/localgovdrupal/localgov_guides/pull/27?

**Comment by finnlewis** [comment]
It looks like @stephen-cox added some sanity checking code for circular references on campaigns, which might also be an issues still.

**Comment by ekes** [comment]
> It looks like @stephen-cox added some sanity checking code for circular references on campaigns, which might also be an issues still.

Campaigns I certainly recommend looking at my branch that just does away with these **** duplicated reverse entity references.

**Comment by ekes** [comment]
> @ekes is this relevant to today's problem on #27?

This is the root cause of the pain. Yes.

**Comment by ekes** [comment]
> > It looks like @stephen-cox added some sanity checking code for circular references on campaigns, which might also be an issues still.
> 
> Campaigns I certainly recommend looking at my branch that just does away with these **** duplicated reverse entity references.

But yes that campaigns patch did also clean up some of what #27 is also doing.
